db:
  development:
    adapter: mysql2
    encoding: utf8
    reconnect: false
    database: posts
    pool: 5
    username: root
    password:
    host: localhost
    timeout: 5000

  production:
    adapter: mysql2
    encoding: utf8
    reconnect: false
    database: posts
    pool: 5
    username: root
    password:
    host: localhost
    timeout: 5000
